//! Static catalog and registry of game events.

use roulette_domain::{EventId, EventTier};

/// Static definition and metadata of an event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EventDef {
    /// Unique stable identifier indexing this event.
    pub id: EventId,
    /// Dramatic rarity tier.
    pub tier: EventTier,
    /// User-facing headline title.
    pub title: &'static str,
    /// Narrative summary describing the flavor and physical fact.
    pub narrative: &'static str,
    /// Branch path depth cost (0 for transitions/dampeners, 1-4 for higher chains).
    pub chain_cost: u32,
    /// Whether this event can inflict lethal or catastrophic damage/elimination.
    pub is_lethal: bool,
}

/// Global registry of known events.
pub struct EventRegistry;

impl EventRegistry {
    /// Returns the static event definition for the given event ID.
    #[must_use]
    #[allow(clippy::too_many_lines)]
    pub fn get(id: &EventId) -> Option<EventDef> {
        match id.0.as_str() {
            "evt_weather_blizzard" => Some(EventDef {
                id: EventId::new("evt_weather_blizzard"),
                tier: EventTier::Epic,
                title: "极寒暴雪",
                narrative: "刺骨暴雪骤降，狂风呼啸，全图水面瞬间凝结成坚冰！",
                chain_cost: 3,
                is_lethal: false,
            }),
            "evt_water_freeze_ice" => Some(EventDef {
                id: EventId::new("evt_water_freeze_ice"),
                tier: EventTier::Uncommon,
                title: "水面凝结",
                narrative: "严寒之下水波停滞，迅速冻结为光滑冰面。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_disoriented_reverse_shot" => Some(EventDef {
                id: EventId::new("evt_disoriented_reverse_shot"),
                tier: EventTier::Uncommon,
                title: "晕头转向",
                narrative: "射手视野昏花，在恍惚中竟然朝相反方向扣动了扳机！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_revolver_misfire" => Some(EventDef {
                id: EventId::new("evt_revolver_misfire"),
                tier: EventTier::Normal,
                title: "撞针空响",
                narrative: "转轮枪发出清脆的卡嗒声，哑火了，现场一片死寂。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_crate_splinter_blast" => Some(EventDef {
                id: EventId::new("evt_crate_splinter_blast"),
                tier: EventTier::Rare,
                title: "木箱爆碎",
                narrative: "木箱瞬间四分五裂，飞溅的破片与冲击波扩散向四周！",
                chain_cost: 2,
                is_lethal: false,
            }),
            "evt_splinter_scratch" => Some(EventDef {
                id: EventId::new("evt_splinter_scratch"),
                tier: EventTier::Normal,
                title: "飞屑划伤",
                narrative: "爆裂的飞屑击中附近隐蔽的玩家，引起一阵惊呼。",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_ice_slide" => Some(EventDef {
                id: EventId::new("evt_ice_slide"),
                tier: EventTier::Uncommon,
                title: "冰面滑行",
                narrative: "踏上光滑的冰面，身形不受控制地顺势向前滑行了一格！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_mine_chain_detonation" => Some(EventDef {
                id: EventId::new("evt_mine_chain_detonation"),
                tier: EventTier::Legendary,
                title: "地壳震荡",
                narrative: "猛烈的爆炸冲击波撕裂地表，波及周边区域！",
                chain_cost: 4,
                is_lethal: true,
            }),
            "evt_dust_settles" => Some(EventDef {
                id: EventId::new("evt_dust_settles"),
                tier: EventTier::Normal,
                title: "烟尘落定",
                narrative: "激荡的冲击波渐渐平息，硝烟与碎屑归于沉寂。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_recoil_knockback" => Some(EventDef {
                id: EventId::new("evt_recoil_knockback"),
                tier: EventTier::Rare,
                title: "后坐力强冲",
                narrative: "转轮手枪超量装药！强大的后坐力将射手反冲倒退一格！",
                chain_cost: 2,
                is_lethal: false,
            }),
            "evt_piercing_slug" => Some(EventDef {
                id: EventId::new("evt_piercing_slug"),
                tier: EventTier::Epic,
                title: "穿甲重弹",
                narrative: "高温穿甲弹带着刺耳呼啸，贯穿了前方掩体！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_sprint_dash" => Some(EventDef {
                id: EventId::new("evt_sprint_dash"),
                tier: EventTier::Uncommon,
                title: "骤然突进",
                narrative: "脚步发力过猛，惯性带着身体顺势向前多冲刺了一格！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_stumble_trip" => Some(EventDef {
                id: EventId::new("evt_stumble_trip"),
                tier: EventTier::Uncommon,
                title: "脚底绊蒜",
                narrative: "踩到碎石脚下一滑狼狈摔倒，未能移动，呆立原地！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_spatial_swap" => Some(EventDef {
                id: EventId::new("evt_spatial_swap"),
                tier: EventTier::Legendary,
                title: "空间对调",
                narrative: "强烈的地磁混乱撕裂空间，玩家与地图上一处随机实体对调了位置！",
                chain_cost: 3,
                is_lethal: false,
            }),
            "evt_crate_surprise_mine" => Some(EventDef {
                id: EventId::new("evt_crate_surprise_mine"),
                tier: EventTier::Epic,
                title: "箱中藏雷",
                narrative: "木箱破裂的瞬间引爆了藏在底部的触发式地雷！",
                chain_cost: 3,
                is_lethal: true,
            }),
            "evt_crate_surprise_medkit" => Some(EventDef {
                id: EventId::new("evt_crate_surprise_medkit"),
                tier: EventTier::Uncommon,
                title: "翻出护盾",
                narrative: "木箱散落开来，里面掉落出了一件崭新的防护单兵盾！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_ice_crack_collapse" => Some(EventDef {
                id: EventId::new("evt_ice_crack_collapse"),
                tier: EventTier::Rare,
                title: "薄冰碎裂",
                narrative: "薄冰承受不住重量轰然破碎，冰面化作深水，玩家落入水中！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_weather_heatwave" => Some(EventDef {
                id: EventId::new("evt_weather_heatwave"),
                tier: EventTier::Epic,
                title: "炙热热浪",
                narrative: "滚滚热浪席卷战场，地图上所有的坚冰瞬间消融化为深水！",
                chain_cost: 2,
                is_lethal: false,
            }),
            "evt_meteor_strike" => Some(EventDef {
                id: EventId::new("evt_meteor_strike"),
                tier: EventTier::Legendary,
                title: "天降陨石",
                narrative: "一颗燃烧的天外陨石轰然砸中地表，摧毁了目标地貌！",
                chain_cost: 3,
                is_lethal: true,
            }),
            "evt_ricochet_deadly" => Some(EventDef {
                id: EventId::new("evt_ricochet_deadly"),
                tier: EventTier::Epic,
                title: "致命跳弹",
                narrative: "子弹撞击掩体后发生致命折射，以刁钻角度扑向了附近存活的玩家！",
                chain_cost: 1,
                is_lethal: true,
            }),
            "evt_sudden_landmine" => Some(EventDef {
                id: EventId::new("evt_sudden_landmine"),
                tier: EventTier::Rare,
                title: "步步惊心",
                narrative: "地表土石崩塌，露出了深埋地下的触发式暗雷并轰然引爆！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_wall_fatal_concussion" => Some(EventDef {
                id: EventId::new("evt_wall_fatal_concussion"),
                tier: EventTier::Rare,
                title: "颅骨碎裂",
                narrative: "全速撞击坚硬的冰冷墙体，猛烈的反冲力当场震碎了颅骨！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_wall_collapse_crush" => Some(EventDef {
                id: EventId::new("evt_wall_collapse_crush"),
                tier: EventTier::Rare,
                title: "坍塌掩埋",
                narrative: "身体猛撞墙体引发承重结构断裂，剥落的沉重巨石轰然将其掩埋！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_wall_rebound_detonation" => Some(EventDef {
                id: EventId::new("evt_wall_rebound_detonation"),
                tier: EventTier::Rare,
                title: "反弹触雷",
                narrative: "高速撞墙后身体失控后仰反弹，后脑重重砸在隐蔽地雷引信上轰然引爆！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_wall_stun_survive" => Some(EventDef {
                id: EventId::new("evt_wall_stun_survive"),
                tier: EventTier::Normal,
                title: "侥幸存活",
                narrative: "撞墙瞬间下意识抬臂护住要害，虽被撞得头破血流、眼冒金星，但侥幸保住一命！",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_wall_breakthrough" => Some(EventDef {
                id: EventId::new("evt_wall_breakthrough"),
                tier: EventTier::Epic,
                title: "破墙而入",
                narrative: "蛮横的体魄与惊人的冲劲竟硬生生震塌了老旧薄墙，在废墟中砸开一条通路！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_pebble_kick" => Some(EventDef {
                id: EventId::new("evt_pebble_kick"),
                tier: EventTier::Normal,
                title: "踢飞碎石",
                narrative: "脚尖碰落了一枚小碎石，骨碌碌滚向远方。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_water_bogged_down" => Some(EventDef {
                id: EventId::new("evt_water_bogged_down"),
                tier: EventTier::Normal,
                title: "深水阻滞",
                narrative: "深水漫过膝盖，水流与淤泥拖拽着脚步，行动受到拖延。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_water_splash" => Some(EventDef {
                id: EventId::new("evt_water_splash"),
                tier: EventTier::Normal,
                title: "水花四溅",
                narrative: "重重踩入水洼溅起大片水花，暴露了移动踪迹！",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_high_ground_vantage" => Some(EventDef {
                id: EventId::new("evt_high_ground_vantage"),
                tier: EventTier::Rare,
                title: "制高优势",
                narrative: "居高临下俯瞰全场，开阔的视野带来了极佳的居高临下心理优势！",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_rockslide_tumble" => Some(EventDef {
                id: EventId::new("evt_rockslide_tumble"),
                tier: EventTier::Normal,
                title: "碎石滑坡",
                narrative: "高地陡坡边缘风化松动，落石滑落让人重心微晃。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_mine_detonation" => Some(EventDef {
                id: EventId::new("evt_mine_detonation"),
                tier: EventTier::Rare,
                title: "地雷引爆",
                narrative: "脚下暗雷引信被彻底触发，轰然引爆！",
                chain_cost: 2,
                is_lethal: true,
            }),
            "evt_mine_dud" => Some(EventDef {
                id: EventId::new("evt_mine_dud"),
                tier: EventTier::Normal,
                title: "哑雷哑火",
                narrative: "脚下暗雷发出清脆咔哒声，但引信受潮失效，虚惊一场！",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_medkit_collect" => Some(EventDef {
                id: EventId::new("evt_medkit_collect"),
                tier: EventTier::Rare,
                title: "装填护盾",
                narrative: "拾取战术护盾模块，能量护盾启动并包裹全身！",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_ice_exit_crack" => Some(EventDef {
                id: EventId::new("evt_ice_exit_crack"),
                tier: EventTier::Normal,
                title: "后蹬碎冰",
                narrative: "借力蹬踏冰面离开，身后薄冰应声龟裂！",
                chain_cost: 1,
                is_lethal: false,
            }),
            "evt_water_exit_surge" => Some(EventDef {
                id: EventId::new("evt_water_exit_surge"),
                tier: EventTier::Normal,
                title: "破水而出",
                narrative: "破开水流带起大片水花登上干燥地面。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_high_ground_leap" => Some(EventDef {
                id: EventId::new("evt_high_ground_leap"),
                tier: EventTier::Normal,
                title: "疾速跃下",
                narrative: "居高临下一跃而下，迅捷落入低地。",
                chain_cost: 0,
                is_lethal: false,
            }),
            "evt_nothing_happens" => Some(EventDef {
                id: EventId::new("evt_nothing_happens"),
                tier: EventTier::Normal,
                title: "风平浪静",
                narrative: "周围空气略显沉寂，暂时没有发生意外。",
                chain_cost: 0,
                is_lethal: false,
            }),
            _ => None,
        }
    }
}
